const INVITEES = [
  { first: "Kyle ", last: "Warzecha", email: "", group: "1" },
  { first: "Jon", last: "Lamb", email: "", group: "2" },
  { first: "Gabby", last: "Sunseri", email: "", group: "2" },
  { first: "Gio", last: "Ramirez", email: "", group: "" },
  { first: "Aleah", last: "Sanchez", email: "", group: "" },
  { first: "Nicolle", last: "Montero", email: "", group: "3" },
  { first: "Eric", last: "Sorger", email: "", group: "" },
  { first: "Emma", last: "Schumacher", email: "", group: "4" },
  { first: "Maddie", last: "Biel", email: "", group: "" },
  { first: "Tamra", last: "Stump", email: "", group: "" },
  { first: "Nate", last: "Peralta", email: "", group: "5" },
  { first: "Kori", last: "Strong", email: "", group: "5" },
  { first: "Chris", last: "Giboney", email: "", group: "6" },
  { first: "Ayush", last: "Luthera", email: "", group: "" },
  { first: "Dryden", last: "Baumfalk", email: "", group: "" },
  { first: "Katie", last: "McMahon", email: "", group: "" },
  { first: "Claire", last: "Boe", email: "", group: "7" },
  { first: "David", last: "Oglesby", email: "", group: "7" },
  { first: "Gabriela", last: "Madina", email: "", group: "" },
  { first: "Cameron", last: "Vallin", email: "", group: "8" },
  { first: "Nate", last: "Heavner", email: "", group: "" },
  { first: "Dom", last: "Colton", email: "", group: "" },
  { first: "Sierra", last: "Spade", email: "", group: "" },
  { first: "Caity", last: "Hall", email: "", group: "9" },
  { first: "Cole", last: "Ferguson", email: "", group: "9" },
  { first: "Dana", last: "Fowler", email: "", group: "" },
  { first: "Patrick", last: "Kasza", email: "", group: "" },
  { first: "Brad", last: "Norris", email: "", group: "" },
  { first: "Coleman", last: "Bryant", email: "", group: "" },
  { first: "Maddie", last: "Clinger", email: "", group: "" },
  { first: "Josh", last: "Spicer", email: "", group: "" },
  { first: "Jessica", last: "Long", email: "", group: "" },
  { first: "Melissa", last: "Devlin", email: "", group: "" },
  { first: "Natorri", last: "Thomas", email: "", group: "" },
  { first: "Alex", last: "Scopel", email: "", group: "10" },
  { first: "May", last: "Maung", email: "", group: "10" },
  { first: "Zin", last: "Maung", email: "", group: "11" },
  { first: "Hannah", last: "Wander", email: "", group: "11" },
  { first: "David", last: "Choe", email: "", group: "" },
  { first: "Hannah", last: "Buds", email: "", group: "" },
  { first: "Alex", last: "Casado", email: "", group: "" },
  { first: "Amanda", last: "Dybal", email: "", group: "12" },
  { first: "Eathan", last: "Long", email: "", group: "12" },
  { first: "Amanda", last: "Hobbs", email: "", group: "" },
  { first: "Rosie", last: "McMahan", email: "", group: "" },
  { first: "Anita", last: "Cuzcano", email: "", group: "" },
  { first: "Emily", last: "Beck", email: "", group: "" },
  { first: "Emily", last: "Durham", email: "", group: "13" },
  { first: "Nate", last: "Bowers", email: "", group: "" },
  { first: "Johana", last: "Sanchez", email: "", group: "" },
  { first: "Jorge ", last: "Tipiana", email: "", group: "" },
  { first: "Kyle", last: "Koval", email: "", group: "" },
  { first: "Raj", last: "Patel", email: "", group: "" },
  { first: "Sam", last: "Moore", email: "", group: "" },
  { first: "Millen", last: "Nguyen", email: "", group: "" },
  { first: "Amber", last: "Breen", email: "", group: "14" },
  { first: "Cassie", last: "Morris", email: "", group: "" },
  { first: "Keegan", last: "Breen", email: "", group: "14" },
  { first: "Keenan", last: "Caminade", email: "", group: "" },
  { first: "Jay", last: "Park", email: "", group: "15" },
  { first: "Paige", last: "Park", email: "", group: "15" },
  { first: "Jade", last: "Brooks", email: "", group: "" },
  { first: "Jackie", last: "Walejko", email: "", group: "16" },
  { first: "Rob", last: "", email: "", group: "16" },
  { first: "Victor", last: "Haymon", email: "", group: "" },
  { first: "Landen", last: "Ross", email: "", group: "17" },
  { first: "Orion", last: "Maynard", email: "", group: "17" },
  { first: "Ryan", last: "Morrison", email: "", group: "" },
  { first: "Edward", last: "Lin", email: "", group: "" },
  { first: "Beth", last: "Salapek", email: "", group: "" },
  { first: "Justin", last: "Eggers", email: "", group: "" },
  { first: "Rachel", last: "Schaeffer", email: "", group: "" },
  { first: "Luke", last: "Adas", email: "", group: "" },
  { first: "Royette", last: "Briones", email: "", group: "" },
  { first: "Zeke", last: "Avila", email: "", group: "" },
  { first: "Amber", last: "Zeiss", email: "", group: "" },
  { first: "Christian", last: "Tobar", email: "", group: "" },
  { first: "Matt", last: "Nelson", email: "", group: "" },
  { first: "Aaron", last: "Sellek", email: "", group: "" },
  { first: "Helen", last: "Hofelt", email: "", group: "" },
  { first: "Beth", last: "Salapek", email: "", group: "" },
  { first: "Wilma", last: "Kivlehen ", email: "", group: "" },
  { first: "Tommy", last: "Justword ", email: "", group: "18" },
  { first: "Tommy", last: "Armstrong", email: "", group: "" },
  { first: "Oriana", last: "Barrios", email: "", group: "18" },
  { first: "Dustin", last: "Rhodes", email: "", group: "" },
  { first: "Alli", last: "Pearl", email: "", group: "" },
  { first: "John", last: "Nguyen", email: "", group: "19" },
  { first: "Freddie", last: "Bravo", email: "", group: "" },
  { first: "Brittany", last: "McCoy", email: "", group: "" },
  { first: "Maddie", last: "Parobek", email: "", group: "" },
  { first: "Michael", last: "Root", email: "", group: "" },
  { first: "Chance", last: "Hoffman", email: "", group: "" },
  { first: "Jason", last: "Blucher", email: "", group: "" },
  { first: "Allision", last: "O'Connor", email: "", group: "" },
  { first: "James ", last: "Oei", email: "", group: "" },
  { first: "Keri", last: "Han", email: "", group: "" },
  { first: "Kathryn", last: "Clark", email: "", group: "" },
  { first: "Ryan", last: "Clark", email: "", group: "" },
  { first: "Josh", last: "Grabski", email: "", group: "" },
  { first: "Andres", last: "Wolfe", email: "", group: "" },
  { first: "Chris", last: "Olson", email: "", group: "" },
  { first: "Marissa", last: "Kuula", email: "", group: "" },
  { first: "Caroline", last: "Noti", email: "", group: "" },
  { first: "Cooper", last: "Grissom", email: "", group: "" },
  { first: "Alyssa", last: "Pitt", email: "", group: "" },
  { first: "Chevy", last: "Flora", email: "", group: "" },
  { first: "Tyler", last: "Nicolas", email: "", group: "" },
  { first: "Yeny Hau ", last: "Chen", email: "", group: "" },
  { first: "Katie", last: "Yi", email: "", group: "" },
  { first: "Jacob", last: "Hendren", email: "", group: "" },
  { first: "Omar ", last: "Landeros", email: "", group: "" },
  { first: "Peyton", last: "Robinson", email: "", group: "" },
  { first: "Keaton", last: "Williams", email: "", group: "13" },
  { first: "Ginny ", last: "Phillips", email: "", group: "" },
  { first: "Aaron", last: "Sellek", email: "", group: "" },
  { first: "Steph", last: "Atkinson ", email: "", group: "19" },
  { first: "Dylan", last: "Dacey", email: "", group: "" },
  { first: "Jacob", last: "Weissert", email: "", group: "" },
  { first: "Marlee", last: "Caregnato", email: "", group: "" },
  { first: "Ismail", last: "Hotaki", email: "", group: "" },
  { first: "Amelia ", last: "Smith ", email: "", group: "" },
  { first: "Becca ", last: "Weiss ", email: "", group: "" },
  { first: "Jillian ", last: "Smith", email: "", group: "" },
  { first: "Kelly ", last: "Kauffman", email: "", group: "" },
  { first: "Abishek", last: "Raman", email: "", group: "" },
  { first: "Albert", last: "Howell", email: "", group: "" },
  { first: "Allison", last: "O'Connor", email: "", group: "" },
  { first: "Andres", last: "Wolfe", email: "", group: "" },
  { first: "Andrew", last: "Gil", email: "", group: "" },
  { first: "Anna", last: "Brand", email: "", group: "" },
  { first: "Antonio", last: "Corona", email: "", group: "" },
  { first: "Benjamin", last: "Graham", email: "", group: "" },
  { first: "Brent", last: "Krueger", email: "", group: "" },
  { first: "Brian", last: "Behrhorst", email: "", group: "" },
  { first: "Bryan", last: "Nelson", email: "", group: "" },
  { first: "Chase", last: "Webber", email: "", group: "" },
  { first: "Chris ", last: "Carlos", email: "", group: "" },
  { first: "Chris", last: "Reusz", email: "", group: "" },
  { first: "Christina", last: "Calderon", email: "", group: "" },
  { first: "Cicily", last: "Wallace", email: "", group: "" },
  { first: "Colin", last: "Medina", email: "", group: "" },
  { first: "Cory", last: "Gensler", email: "", group: "" },
  { first: "Damon", last: "Craig", email: "", group: "" },
  { first: "Dan", last: "Slivka", email: "", group: "" },
  { first: "Greg ", last: "Muholland", email: "", group: "" },
  { first: "Dan", last: "Ross", email: "", group: "" },
  { first: "Daniel", last: "Koengsperger", email: "", group: "" },
  { first: "Daniel", last: "Schneider", email: "", group: "" },
  { first: "Danielle", last: "Keaton", email: "", group: "" },
  { first: "Darin", last: "Trip", email: "", group: "" },
  { first: "Emeli", last: "Colorado", email: "", group: "" },
  { first: "Emma", last: "De Neef", email: "", group: "" },
  { first: "Erica", last: "Hinrichs", email: "", group: "" },
  { first: "Gabriel", last: "Doriman", email: "", group: "" },
  { first: "Grayson", last: "Walter", email: "", group: "" },
  { first: "Greg ", last: "Jonker", email: "", group: "" },
  { first: "Ian", last: "Kehoe", email: "", group: "" },
  { first: "Isabel", last: "Keddy-Hector", email: "", group: "" },
  { first: "Isabella", last: "Kelsey", email: "", group: "" },
  { first: "Jared", last: "Solis", email: "", group: "" },
  { first: "Jeffery", last: "Daniel", email: "", group: "" },
  { first: "Jessi", last: "Atallah", email: "", group: "" },
  { first: "Juliet", last: "King", email: "", group: "" },
  { first: "Justin", last: "Guinta", email: "", group: "" },
  { first: "Kaley", last: "Palanjian", email: "", group: "" },
  { first: "Patrick ", last: "Deloach", email: "", group: "" },
  { first: "Kamaran", last: "McClanahan", email: "", group: "" },
  { first: "Katie", last: "Brooks", email: "", group: "" },
  { first: "Katie", last: "Day", email: "", group: "" },
  { first: "Katie", last: "Mclamb", email: "", group: "" },
  { first: "Katya", last: "Fox", email: "", group: "" },
  { first: "Kayla", last: "Pattie", email: "", group: "" },
  { first: "Kaylee", last: "Barber", email: "", group: "" },
  { first: "Kris", last: "McGlothlin", email: "", group: "" },
  { first: "Kya", last: "Moore", email: "", group: "" },
  { first: "Kyle", last: "Fegurgur", email: "", group: "" },
  { first: "Leonel", last: "Santana", email: "", group: "" },
  { first: "Lindsey", last: "Oberacker", email: "", group: "" },
  { first: "Liz", last: "Enck", email: "", group: "" },
  { first: "Luca", last: "Bernardo Nucci", email: "", group: "" },
  { first: "Luke", last: "Callaghan", email: "", group: "" },
  { first: "Malofou", last: "Tavita", email: "", group: "" },
  { first: "Maria", last: "Davis", email: "", group: "" },
  { first: "Megan", last: "Ryals", email: "", group: "" },
  { first: "Melissa", last: "Cochran", email: "", group: "" },
  { first: "Michael", last: "Gh", email: "", group: "" },
  { first: "Michael", last: "Root", email: "", group: "" },
  { first: "Myrnelix", last: "Fontanez", email: "", group: "" },
  { first: "Nancy", last: "Cruz", email: "", group: "" },
  { first: "Natalia", last: "Diaz", email: "", group: "" },
  { first: "Nikki Maria-Kay", last: "Mehan", email: "", group: "" },
  { first: "Paige", last: "Sportss", email: "", group: "" },
  { first: "Pat", last: "Skelton", email: "", group: "" },
  { first: "Angie ", last: "Torres", email: "", group: "" },
  { first: "Paul", last: "Callaghan", email: "", group: "" },
  { first: "Rachel", last: "Bramble", email: "", group: "" },
  { first: "Ray", last: "Lee", email: "", group: "" },
  { first: "Ryan", last: "Sea", email: "", group: "" },
  { first: "Savannah ", last: "Bridgers", email: "", group: "" },
  { first: "Shannen", last: "Johnson", email: "", group: "" },
  { first: "Shira", last: "Wells", email: "", group: "" },
  { first: "Skylar", last: "Ogden", email: "", group: "" },
  { first: "Terri", last: "Berri", email: "", group: "" },
  { first: "Victor", last: "Sealey", email: "", group: "" },
  { first: "Walter", last: "Pati", email: "", group: "" },
  { first: "Lazaro", last: "Leon", email: "", group: "" },
  { first: "Taylor", last: "Stewart", email: "", group: "" },
  { first: "Victor ", last: "Vo", email: "", group: "" },
  { first: "John", last: "Tee", email: "", group: "" },
  { first: "Phoebe", last: "Havenaar", email: "", group: "" },
  { first: "Bharath", last: "Myla", email: "", group: "" },
  { first: "Katie", last: "Houston", email: "", group: "" },
  { first: "Alex", last: "Liu", email: "", group: "" },
  { first: "Kenny", last: "Nguyen", email: "", group: "22" },
  { first: "Nichole", last: "Ford", email: "", group: "22" },
  { first: "Matthew", last: "Henke", email: "", group: "" },
  { first: "Haze", last: "Nguyen", email: "", group: "" },
  { first: "Connor", last: "Carino", email: "", group: "" },
  { first: "Ernesto", last: "Gonzalez", email: "", group: "" },
  { first: "Ben", last: "Vasquez", email: "", group: "" },
  { first: "Nick", last: "Shirley", email: "", group: "20" },
  { first: "Rachel", last: "Polak", email: "", group: "20" },
  { first: "Delilah", last: "Renken", email: "", group: "" },
  { first: "Josh", last: "Biller", email: "", group: "" },
  { first: "Maredith", last: "Devlin", email: "", group: "21" },
  { first: "Joseph", last: "Hildebrand", email: "", group: "21" },
  { first: "Willa", last: "Brooks", email: "", group: "" },
];
